In [2]:
import pandas as pd
import numpy as np
import xgboost as xgb
import lightgbm as lgb
import matplotlib.pyplot as plt

In [3]:
train = pd.read_csv('./data/jinnan_round1_train_20181227.csv', encoding='gb18030')
test = pd.read_csv('./data/jinnan_round1_testA_20181227.csv', encoding='gb18030')

In [4]:
train.describe()

,A1,A2,A3,A4,A6,A8,A10,A12,A13,A15,...,A27,B1,B2,B3,B6,B8,B12,B13,B14,收率
count,1396.000000,42.0,1354.000000,1396.000000,1396.000000,149.000000,1396.000000,1396.000000,1396.000000,1396.000000,...,1396.000000,1386.000000,1394.000000,1394.000000,1396.000000,1395.000000,1395.000000,1395.000000,1396.000000,1396.000000
mean,298.853868,125.0,403.515510,705.974212,28.287751,78.818792,100.861032,102.641834,0.199907,103.829370,...,74.396848,334.452742,3.454412,3.500072,72.065186,43.709677,1020.215054,0.149419,410.403295,0.923244
std,10.130552,0.0,13.348093,53.214754,6.742765,2.683920,0.905198,0.915387,0.002524,0.963639,...,3.044490,105.120753,0.388585,0.002678,9.161986,4.338396,205.920155,0.008213,26.018410,0.030880
min,200.000000,125.0,270.000000,470.000000,17.000000,70.000000,100.000000,98.000000,0.120000,100.000000,...,45.000000,3.500000,0.150000,3.500000,40.000000,20.000000,400.000000,0.030000,40.000000,0.624000
25%,300.000000,125.0,405.000000,700.000000,24.000000,80.000000,100.000000,102.000000,0.200000,103.000000,...,73.000000,320.000000,3.500000,3.500000,65.000000,45.000000,800.000000,0.150000,400.000000,0.902000
50%,300.000000,125.0,405.000000,700.000000,29.000000,80.000000,101.000000,103.000000,0.200000,104.000000,...,73.000000,320.000000,3.500000,3.500000,78.000000,45.000000,1200.000000,0.150000,400.000000,0.925000
75%,300.000000,125.0,405.000000,700.000000,30.000000,80.000000,102.000000,103.000000,0.200000,104.000000,...,77.000000,330.000000,3.500000,3.500000,80.000000,45.000000,1200.000000,0.150000,420.000000,0.943000
max,300.000000,125.0,405.000000,980.000000,97.000000,82.000000,103.000000,107.000000,0.200000,109.000000,...,80.000000,1200.000000,3.600000,3.600000,80.000000,73.000000,1200.000000,0.150000,460.000000,1.000800

In [5]:
test.describe()

,A1,A2,A3,A4,A6,A8,A10,A12,A13,A15,...,A25,A27,B1,B2,B3,B6,B8,B12,B13,B14
count,150.000000,3.0,147.000000,150.000000,150.000000,18.000000,150.000000,150.000000,1.500000e+02,150.000000,...,149.000000,149.000000,149.000000,150.000000,150.0,150.000000,150.000000,150.000000,1.500000e+02,150.000000
mean,299.333333,125.0,404.081633,704.066667,29.373333,80.111111,100.866667,102.774667,2.000000e-01,103.812667,...,75.436242,74.275168,343.557047,3.433000,3.5,72.073333,43.726667,1016.000000,1.500000e-01,414.733333
std,8.164966,0.0,11.134612,43.782511,8.737443,0.323381,0.924438,0.877855,5.012741e-16,1.125500,...,4.849522,4.021663,125.397066,0.470571,0.0,9.347933,4.247220,208.568145,2.227885e-16,36.535294
min,200.000000,125.0,270.000000,470.000000,18.000000,80.000000,100.000000,101.000000,2.000000e-01,101.000000,...,70.000000,45.000000,190.000000,0.150000,3.5,40.000000,20.000000,400.000000,1.500000e-01,280.000000
25%,300.000000,125.0,405.000000,700.000000,24.000000,80.000000,100.000000,102.000000,2.000000e-01,103.000000,...,70.000000,73.000000,320.000000,3.500000,3.5,65.000000,45.000000,800.000000,1.500000e-01,400.000000
50%,300.000000,125.0,405.000000,700.000000,29.000000,80.000000,101.000000,103.000000,2.000000e-01,104.000000,...,78.000000,73.000000,320.000000,3.500000,3.5,78.000000,45.000000,1200.000000,1.500000e-01,400.000000
75%,300.000000,125.0,405.000000,700.000000,30.000000,80.000000,102.000000,103.000000,2.000000e-01,104.000000,...,80.000000,77.000000,340.000000,3.500000,3.5,80.000000,45.000000,1200.000000,1.500000e-01,420.000000
max,300.000000,125.0,405.000000,980.000000,80.000000,81.000000,103.000000,106.000000,2.000000e-01,107.000000,...,90.000000,80.000000,1200.000000,3.500000,3.5,80.000000,50.000000,1200.000000,1.500000e-01,785.000000

In [6]:
%matplotlib inline

In [7]:
import time
time_name = time.strftime('%Y%m%d%H%M',time.localtime(time.time()))

In [8]:
time_name

'201901071601'

In [9]:
train.head()

,样本id,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,B6,B7,B8,B9,B10,B11,B12,B13,B14,收率
0,sample_1528,300,NaN,405.0,700,13:30:00,38.0,NaN,NaN,15:30:00,...,65,11:30:00,45.0,11:30-13:00,14:00-15:30,NaN,800.0,0.15,400,0.879
1,sample_1698,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,6:00:00,45.0,6:00-7:30,7:30-9:00,9:00-10:00,1200.0,0.15,400,0.902
2,sample_639,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.936
3,sample_483,300,NaN,405.0,700,1:30:00,38.0,NaN,NaN,3:00:00,...,65,18:00:00,45.0,19:00-20:30,21:30-23:00,NaN,800.0,0.15,400,0.902
4,sample_617,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.983

In [11]:
train

,样本id,A1,A2,A3,A4,A5,A6,A7,A8,A9,...,B6,B7,B8,B9,B10,B11,B12,B13,B14,收率
0,sample_1528,300,NaN,405.0,700,13:30:00,38.0,NaN,NaN,15:30:00,...,65,11:30:00,45.0,11:30-13:00,14:00-15:30,NaN,800.0,0.15,400,0.879
1,sample_1698,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,6:00:00,45.0,6:00-7:30,7:30-9:00,9:00-10:00,1200.0,0.15,400,0.902
2,sample_639,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.936
3,sample_483,300,NaN,405.0,700,1:30:00,38.0,NaN,NaN,3:00:00,...,65,18:00:00,45.0,19:00-20:30,21:30-23:00,NaN,800.0,0.15,400,0.902
4,sample_617,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.983
5,sample_373,300,NaN,405.0,700,2:00:00,39.0,2:30:00,80.0,3:30:00,...,65,3:00:00,45.0,3:00-4:30,5:30-7:00,NaN,800.0,0.15,420,0.935
6,sample_577,300,NaN,405.0,700,8:00:00,29.0,NaN,NaN,10:00:00,...,80,19:00:00,45.0,19:00-20:30,20:30-22:00,22:00-23:00,1200.0,0.15,400,0.902
7,sample_212,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.891
8,sample_521,300,NaN,405.0,700,17:30:00,21.0,NaN,NaN,19:00:00,...,65,6:30:00,45.0,6:30-8:00,8:30-10:00,NaN,800.0,0.15,420,0.947
9,sample_1026,300,NaN,405.0,700,11:00:00,21.0,NaN,NaN,12:30:00,...,64,2:00:00,50.0,6:00-7:30,8:00-9:30,NaN,800.0,0.15,400,0.902
10,sample_1743,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,78,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:30,1200.0,0.15,400,0.936
11,sample_1493,300,NaN,405.0,700,21:00:00,37.0,21:20:00,80.0,23:00:00,...,65,21:00:00,30.0,21:00-22:30,23:00-0:30,NaN,800.0,0.15,400,0.891
12,sample_1613,300,NaN,405.0,700,11:00:00,33.0,NaN,NaN,12:30:00,...,65,4:00:00,50.0,4:00-5:30,6:00-7:30,NaN,800.0,0.15,400,0.891
13,sample_621,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,74,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.947
14,sample_1269,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.925
15,sample_1037,300,NaN,405.0,700,21:00:00,21.0,NaN,NaN,22:30:00,...,65,13:00:00,45.0,14:00-15:30,16:30-18:00,NaN,800.0,0.15,400,0.902
16,sample_1736,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,420,0.971
17,sample_97,300,NaN,405.0,700,16:00:00,29.0,NaN,NaN,18:00:00,...,80,21:00:00,45.0,3:00-4:30,4:30-6:00,6:00-7:00,1200.0,0.15,400,0.902
18,sample_642,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.913
19,sample_179,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,78,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.925
20,sample_759,300,NaN,405.0,700,4:30:00,27.0,NaN,NaN,6:30:00,...,80,15:30:00,45.0,15:30-19:00,NaN,NaN,1200.0,0.15,440,0.930
21,sample_812,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,0.930
22,sample_1395,300,NaN,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-5:00,NaN,NaN,1200.0,0.15,440,0.930
23,sample_922,300,NaN,405.0,700,19:30:00,38.0,19:40:00,80.0,21:00:00,...,45,21:00:00,40.0,21:30-23:0,23:30-1:00,NaN,800.0,0.15,420,0.947
24,sample_514,300,NaN,405.0,700,11:00:00,26.0,NaN,NaN,12:30:00,...,65,8:00:00,45.0,8:00-9:30,10:00-11:30,NaN,800.0,0.15,420,0.935
25,sample_72,300,NaN,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,78,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.971
26,sample_1344,300,NaN,405.0,700,6:00:00,30.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,0.930
27,sample_582,300,NaN,405.0,700,9:30:00,20.0,NaN,NaN,11:30:00,...,65,19:30:00,45.0,19:30-20:30,21:30-22:00,NaN,1200.0,0.15,420,0.935
28,sample_1002,300,NaN,405.0,700,14:00:00,21.0,NaN,NaN,15:00:00,...,60,4:00:00,39.0,4:30-6:00,7:00-8:00,NaN,800.0,0.15,380,0.878
29,sample_1079,300,NaN,405.0,700,1:00:00,27.0,NaN,NaN,2:30:00,...,65,22:00:00,45.0,0:00-1:30,2:30-4:00,NaN,800.0,0.15,400,0.902
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1366,sample_73,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.902
1367,sample_846,300,125.0,NaN,980,23:30:00,25.0,NaN,NaN,1:00:00,...,60,19:30:00,40.0,20:30-22:00,22:30-0:00,NaN,800.0,0.15,400,0.902
1368,sample_538,300,NaN,405.0,700,1:00:00,28.0,NaN,NaN,2:30:00,...,65,22:00:00,45.0,0:00-1:30,2:30-4:00,NaN,800.0,0.15,400,0.902
1369,sample_1702,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,6:00:00,45.0,6:00-7:30,7:30-9:00,9:00-10:00,1200.0,0.15,420,0.959
1370,sample_850,300,125.0,NaN,980,16:00:00,24.0,NaN,NaN,17:30:00,...,65,10:00:00,40.0,12:00-13:30,14:00-15:30,NaN,800.0,0.15,390,0.890
1371,sample_1625,300,NaN,405.0,700,1:00:00,27.0,NaN,NaN,2:30:00,...,65,20:00:00,50.0,20:00-22:00,23:00-1:00,NaN,800.0,0.15,400,0.902
1372,sample_175,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.947
1373,sample_88,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.902
1374,sample_552,300,NaN,405.0,700,18:00:00,21.0,NaN,NaN,19:30:00,...,65,14:30:00,50.0,14:30-16:00,16:30-18:00,NaN,800.0,0.15,440,0.980
1375,sample_1511,300,NaN,405.0,700,15:00:00,21.0,NaN,NaN,16:00:00,...,60,23:30:00,50.0,23:30-0:30,1:30-2:30,NaN,800.0,0.15,400,0.902
1376,sample_706,300,NaN,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,76,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.925
1377,sample_315,300,NaN,405.0,700,6:30:00,21.0,7:00:00,73.0,8:20:00,...,60,8:00:00,28.0,8:00-9:30,10:00-11:30,NaN,800.0,0.15,400,0.891
1378,sample_1421,300,NaN,405.0,700,23:30:00,24.0,NaN,NaN,1:00:00,...,60,19:30:00,40.0,20:30-22:0,23:00-1:00,NaN,800.0,0.15,400,0.891
1379,sample_601,300,NaN,405.0,700,0:30:00,23.0,NaN,NaN,3:30:00,...,65,13:00:00,45.0,13:00-14:00,15:00-16:00,NaN,800.0,0.15,400,0.902
1380,sample_1497,300,NaN,405.0,700,12:30:00,37.0,12:40:00,80.0,14:20:00,...,65,13:00:00,30.0,13:00-14:30,15:00-16:30,NaN,800.0,0.15,400,0.902
1381,sample_1095,300,NaN,405.0,700,12:00:00,26.0,NaN,NaN,13:30:00,...,65,8:00:00,45.0,9:30-11:00,12:00-13:30,NaN,800.0,0.15,420,0.935
1382,sample_600,300,NaN,405.0,700,16:00:00,23.0,NaN,NaN,18:00:00,...,62,3:30:00,40.0,4:00-5:30,7:00-8:00,NaN,800.0,0.15,400,0.902
1383,sample_1829,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,79,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,400,0.925
1384,sample_1779,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,420,0.983
1385,sample_278,300,NaN,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-5:00,NaN,NaN,1200.0,0.15,460,0.973
1386,sample_1748,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,78,17:00:00,45.0,17:00-18:30,18:30-20:00,20:00-21:00,1200.0,0.15,420,0.971
1387,sample_1034,300,NaN,405.0,700,15:00:00,21.0,NaN,NaN,16:30:00,...,65,8:00:00,45.0,9:30-11:00,12:00-13:30,NaN,800.0,0.15,400,0.947
1388,sample_1384,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,11:00:00,45.0,1:00-5:00,NaN,NaN,1200.0,0.15,440,0.943
1389,sample_1732,300,NaN,405.0,700,22:00:00,30.0,NaN,NaN,0:00:00,...,78,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,400,0.958
1390,sample_764,300,NaN,405.0,700,14:00:00,30.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-4:30,NaN,NaN,1200.0,0.15,460,0.973
1391,sample_836,300,NaN,405.0,700,6:00:00,28.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-21:00,NaN,NaN,1200.0,0.15,440,0.930
1392,sample_1217,300,NaN,405.0,700,22:00:00,29.0,NaN,NaN,0:00:00,...,80,9:00:00,45.0,9:00-10:30,10:30-12:00,12:00-13:00,1200.0,0.15,420,0.971
1393,sample_1654,300,NaN,405.0,700,14:00:00,29.0,NaN,NaN,16:00:00,...,80,1:00:00,45.0,1:00-2:30,2:30-4:00,4:00-5:00,1200.0,0.15,400,0.891
1394,sample_560,300,NaN,405.0,700,18:00:00,29.0,NaN,NaN,20:00:00,...,80,5:00:00,45.0,5:00-6:30,6:30-8:00,8:00-9:00,1200.0,0.15,400,0.902
1395,sample_685,300,NaN,405.0,700,6:00:00,29.0,NaN,NaN,8:00:00,...,80,17:00:00,45.0,17:00-18:30,18:00-20:00,20:00-21:00,1200.0,0.15,400,0.913